<p>함수 solution은 정수 n을 매개변수로 입력받습니다. n의 각 자릿수를 큰것부터 작은 순으로 정렬한 새로운 정수를 리턴해주세요. 예를들어 n이 118372면 873211을 리턴하면 됩니다.</p>

<h5>제한 조건</h5>

<ul>
<li><code>n</code>은 1이상 8000000000 이하인 자연수입니다.</li>
</ul>

<h5>입출력 예</h5>

<table class="table">
<thead><tr>
<th>n</th>
<th style="text-align: center">return</th>
</tr>
</thead>
<tbody><tr>
<td>118372</td>
<td style="text-align: center">873211</td>
</tr>
</tbody>
</table>

In [29]:
def solution(n:int):
    n=str(n)
    value=[]
    answer=''
   
    for i in n:
        value.append(i)
        
    value.sort(reverse=True)
    for j in value:
        answer+=j
    
    return int(answer)

In [30]:
solution(118372)

873211